/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --env-interface CloudflareEnv --include-runtime false` (hash: d9c53ca7654893b7ddaf8fea1795b8ea)
interface __BaseEnv_CloudflareEnv {
	DB: D1Database;
	AI: Ai;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
